<?php
$e2g_lang['spanish'] = array (
    'add_err' => 'no ha sido añadido.',
    'added' => 'añadido.',
    'back' => 'Atrás',
    'comment' => 'El scripto de instalación creará automáticamente Snippet y todas las tablas del db. &lt;br /&gt;&lt;br /&gt; Si está actualizando desde la versión anterior de instalación (&lt;1.3.6-alpha2), &lt;b style=&quot;color:red;&quot;&gt; esto también Cambiará el Nombre&lt;/b&gt; de todas las carpetas y nombres de archivos a sus nombres originales.&lt;br /&gt;Haciendo copias de seguridad de db SQL y los archivos de la Galería &lt;b style=&quot;color:red;&quot;&gt;Antes de la Actualización&lt;/b&gt; es altamente recomendable.&lt;br /&gt;¡Usted ha sido advertido!',
    'comment1' => 'Ruta de acceso a carpeta, &lt;b class=\&quot;warning\&quot;&gt;con barra final&lt;/b&gt;, donde las imágenes se guardarán.&lt;br /&gt; &lt;span id=&quot;result_box&quot;&gt;&lt;span title=&quot;&quot;&gt;por ejemplo&lt;/span&gt;&lt;/span&gt;: assets/gallery/.',
    'create_dir_err' => 'No se puede crear la carpeta',
    'create_err' => 'no ha sido creada.',
    'created' => 'ha sido creada con éxito.',
    'credit_lang_file' => 'Language file credit',
    'credit_lang_file_author' => 'risingisland',
    'credit_lang_file_date' => '03 de noviembre, 2017',
    'credit_lang_file_version' => '2.1',
    'data' => 'Datos',
    'data_updated_err' => 'datos no actualizados',
    'data_updated_suc' => 'datos actualizado',
    'del_inst_dir' => 'Eliminar carpeta de instalación',
    'dir_created' => 'La carpeta ha sido creada',
    'dir_exists' => 'La carpeta ya existe',
    'empty_dir' => 'carpeta no se establece',
    'field' => 'Campo',
    'install' => 'Instalación',
    'mod_update_err' => 'No se puede actualizar el módulo',
    'mod_updated' => 'El módulo se ha actualizado',
    'ok' => 'Instalar',
    'path' => 'Ruta',
    'plugin_add_err' => 'No se pudo agregar el plug-in',
    'plugin_added' => 'Plugin creado',
    'plugin_updated' => 'El Plugin se actualizo',
    'rename' => 'nombre cambiado.',
    'rename_err' => 'nombre no ha sido cambiado.',
    'restore_err' => 'Ha habido un error al intentar restaurar',
    'restore_suc' => 'Nombres de las galerías restaurada',
    'snippet_add_err' => 'No se puede crear el snippet',
    'snippet_added' => 'Ha sido creado el snippet',
    'snippet_update_err' => 'No se puede actualizar el snippet',
    'snippet_updated' => 'El snippet se ha actualizado',
    'submit' => 'Guardar',
    'success' => 'Instalado con éxito',
    'system_check' => 'Comprobación del sistema',
    'table' => 'Tabla',
    'upgrade_err' => 'no se pudo actualizar.',
    'upgraded' => 'actualizado con éxito.'
);
