<?php
$e2g_lang['spanish'] = array (
	'captcha_err' => 'Código inválido',
	'code' => 'Código',
	'comment_add' => 'Añdir un comentario',
	'comment_add_err' => 'Ha habido un &nbsp;error al intentar publicar el comentario',
	'comment_added' => 'El comentario ha sido añadido',
	'credit_lang_file' => 'Language file credit',
	'credit_lang_file_author' => 'Cx2, Temus, goldsky, risingisland',
	'credit_lang_file_date' => 'October 6, 2010',
	'credit_lang_file_version' => '2.1',
	'email' => 'Email',
	'email_err' => 'El email no es válido',
	'comment_empty_name_comment' => 'You must enter your name and comment',
	'comment_empty_name' => 'Debe introducir su nombre y comentario',
	'comment_empty_comment' => 'You must enter any comment',
	'name' => 'Nombre',
	'notify' => 'Notifiqueme de las respuestas',
	'pages' => 'Páginas',
	'send_btn' => 'Añadir comentario',
	'submit' => 'Guardar',
	'title' => 'Comentarios',
	'usercomment' => 'Su comentario',
	'waitforapproval' => 'Su comentario será esperar a la aprobación',
	'captcha_vericode_err' => 'Incorrect form code. Please enter the correct code displayed by the image.',
	'comments_delay' => 'You cannot add a new comment so soon.'
);
