<?php
$e2g_lang['spanish'] = array (
    'captcha_err' => 'Código inválido',
    'captcha_vericode_err' => 'Código de forma incorrecta. Por favor ingrese el código correcto que muestra la imagen.',
    'code' => 'Código',
    'comment_add' => 'Añdir un comentario',
    'comment_add_err' => 'Ha habido un  error al intentar publicar el comentario',
    'comment_added' => 'El comentario ha sido añadido',
    'comment_empty_comment' => 'Debes ingresar un comentario',
    'comment_empty_name' => 'Debe introducir su nombre y comentario',
    'comment_empty_name_comment' => 'Debes ingresar tu nombre y comentario',
    'comments_delay' => 'No puedes agregar un nuevo comentario tan pronto.',
    'credit_lang_file' => 'Language file credit',
    'credit_lang_file_author' => 'risingisland',
    'credit_lang_file_date' => '03 de noviembre, 2017',
    'credit_lang_file_version' => '2.1',
    'email' => 'Email',
    'email_err' => 'El email no es válido',
    'name' => 'Nombre',
    'notify' => 'Notifiqueme de las respuestas',
    'pages' => 'Páginas',
    'send_btn' => 'Añadir comentario',
    'submit' => 'Save',
    'title' => 'Comentarios',
    'usercomment' => 'Su comentario',
    'waitforapproval' => 'Su comentario será esperar a la aprobación'
);
